"""add_domain_and_attachments_to_project

Revision ID: 058279e08973
Revises: 8b78e6578b97
Create Date: 2026-04-09 14:04:16.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '058279e08973'
down_revision: Union[str, Sequence[str], None] = '8b78e6578b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('attachments_url', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'attachments_url')
    op.drop_column('projects', 'domain')
    # ### end Alembic commands ###
