"""add_agent_details_jsonb

Revision ID: e8a9b0c1d2f3
Revises: c6f8afc3b4a3
Create Date: 2026-04-09 01:39:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8a9b0c1d2f3'
down_revision: Union[str, None] = 'c6f8afc3b4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('intake_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('agent_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'agent_outputs')
    op.drop_column('applications', 'intake_details')
    # ### end Alembic commands ###
